#!/bin/bash
touchpadDisable
xset r rate 450 35
xset s 240 60
setxkbmap -option caps:escape
synclient TapButton1=1 TapButton2=2
numlockx on
redshift_toggle.sh silent
[[ -f "$HOME/.config/i3/wallpaper" ]] \
    && xwallpaper --zoom "$HOME/.config/i3/wallpaper"
compton &
xss-lock -n dim-screen.sh lock &
